spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestion_librairie
    username: postgres
    password: dimithry
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostagreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true